# -*- coding: utf-8 -*-
"""calculations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QREDFL5c4FDqnfuzyf-z5MCRrA4i2eB5
"""

import numpy as np
from .config import RCA_RULES, PF_RUL_THRESHOLD, ITHD_RUL_THRESHOLD, SOILING_LOSS_THRESHOLD

def calculate_rul(current_value, critical_threshold, rate_of_change):
    '''Calculates Remaining Useful Life (RUL) in days.'''
    if abs(rate_of_change) < 1e-6 or np.isnan(rate_of_change):
        return None

    if (critical_threshold > current_value and rate_of_change < 0) or \
       (critical_threshold < current_value and rate_of_change > 0):
        if (current_value >= critical_threshold and critical_threshold >= 1) or \
           (current_value <= critical_threshold and critical_threshold < 1):
            return 0.0

    if critical_threshold > 1.0:
        rul_days = (critical_threshold - current_value) / rate_of_change
    else:
        rul_days = (current_value - critical_threshold) / abs(rate_of_change)

    return max(0.0, rul_days)

def classify(v_thd_instant, i_thd_instant, pf_instant):
    '''Applies RCA rules to instant data.'''
    for label, rule in RCA_RULES.items():
        if rule(v_thd_instant, i_thd_instant, pf_instant):
            return label
    return "Undiagnosed Fault"

def run_predictive_analysis(ithd_90d, ithd_7d, pf_14d, ithd_rate, pf_rate, kwh_forecast, kwh_actual):
    '''Executes all PM/RUL logic.'''
    alerts = []

    rul_ithd = calculate_rul(ithd_7d, 20.0, ithd_rate)
    if rul_ithd is not None and rul_ithd <= ITHD_RUL_THRESHOLD:
        status = 'CRITICAL' if rul_ithd < 5 else 'WARNING'
        alerts.append({
            'Status': status,
            'Type': 'ITHD Trend',
            'Prognosis': f"ITHD RUL: *{rul_ithd:.1f} days*. Expect failure (ITHD > 20.0%) soon. Rate: {ithd_rate:.3f}%/day."
        })
    elif ithd_7d > 15.0:
        alerts.append({
            'Status': 'WARNING',
            'Type': 'High ITHD',
            'Prognosis': f"7-Day Avg ITHD is high ({ithd_7d:.2f}%) but trend is stable."
        })

    rul_pf = calculate_rul(pf_14d, PF_RUL_THRESHOLD, pf_rate)
    if rul_pf is not None and rul_pf <= 14.0 and pf_14d < 0.90:
        status = 'CRITICAL' if rul_pf < 7 else 'WARNING'
        alerts.append({
            'Status': status,
            'Type': 'PF Degradation',
            'Prognosis': f"PF RUL: *{rul_pf:.1f} days*. Power Factor expected to drop below {PF_RUL_THRESHOLD} soon. Rate: {pf_rate:.4f}/day."
        })

    yield_loss_percent = 1.0 - (kwh_actual / kwh_forecast)
    if yield_loss_percent > SOILING_LOSS_THRESHOLD:
        status = 'CRITICAL' if yield_loss_percent > 0.15 else 'WARNING'
        alerts.append({
            'Status': status,
            'Type': 'Yield Loss/Soiling',
            'Prognosis': f"Actual power is *{yield_loss_percent*100:.1f}% less* than forecasted. Possible severe soiling or non-harmonic fault."
        })

    return alerts