# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QREDFL5c4FDqnfuzyf-z5MCRrA4i2eB5
"""

# Configuration and Thresholds

ITHD_RUL_THRESHOLD = 10.0
PF_RUL_THRESHOLD = 0.84
SOILING_LOSS_THRESHOLD = 0.10

# RCA Rules
RCA_RULES = {
    "Harmonic disortion ": lambda v, i, pf: i > 25.0 and v < 5.0,
    "System Resonance ": lambda v, i, pf: v > 5.0 and i > 15.0,
    "Low Power Factor (Reactive Load)": lambda v, i, pf: pf < 0.83,
    "Normal Operation": lambda v, i, pf: True
}

ACTION_MAPPING = {
    "Harmonic disortion ": "Inspect load-side filters and reactive compensation equipment.",
    "System Resonance ": "Install Active Harmonic Filiter AHF for active damping.",
    "Low Power Factor (Reactive Load)": "Activate or repair Power Factor Correction (PFC) banks or use VFD to improve the load.",
    "Normal Operation": "Continue monitoring."
}

PRIORITY_MAPPING = {
    "Harmonic disortion ": "High",
    "System Resonance ": "Urgent",
    "Low Power Factor (Reactive Load)": "Medium",
    "Normal Operation": "Low"
}

# Fixed simulation rates
SIM_ITHD_RATE = 0.067
SIM_PF_RATE = -0.00167