# -*- coding: utf-8 -*-
"""visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QREDFL5c4FDqnfuzyf-z5MCRrA4i2eB5
"""

import pandas as pd
import numpy as np
from datetime import datetime
import streamlit as st

def generate_placeholder_data(key_metric, base_value=None):
    '''Generates time-series data for visualization.'''
    from datetime import datetime, timedelta

    end_date = datetime.now()
    start_date = end_date - timedelta(days=6)
    dates = pd.date_range(start_date, end_date, freq='D')

    if 'ITHD' in key_metric:
        base = base_value if base_value else 9.5
        trend = np.linspace(base - 1.0, base, len(dates)) + np.random.randn(len(dates)) * 0.5
    elif 'PF' in key_metric:
        base = base_value if base_value else 0.88
        trend = np.linspace(base + 0.01, base, len(dates)) + np.random.randn(len(dates)) * 0.005
    elif 'kWh' in key_metric:
        base = base_value if base_value else 29.75
        trend = np.linspace(base - 5, base, len(dates)) + np.random.randn(len(dates)) * 1.5

    df = pd.DataFrame({
        'Date': dates,
        key_metric: trend
    }).set_index('Date')
    return df

def apply_custom_css():
    '''Applies custom CSS styling to the app.'''
    st.markdown('''
    <style>
        .main-title {
            font-size: 2.5rem;
            font-weight: 700;
            background: linear-gradient(120deg, #f6d365 0%, #fda085 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            margin-bottom: 0.5rem;
        }

        .section-header {
            background: linear-gradient(90deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 1rem 1.5rem;
            border-radius: 10px;
            margin: 1.5rem 0 1rem 0;
            font-size: 1.3rem;
            font-weight: 600;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }

        .status-badge {
            display: inline-block;
            padding: 0.4rem 1rem;
            border-radius: 20px;
            font-weight: 600;
            font-size: 0.9rem;
            margin: 0.5rem 0;
        }

        .status-normal {
            background: #d4edda;
            color: #155724;
        }

        .status-warning {
            background: #fff3cd;
            color: #856404;
        }

        .status-critical {
            background: #f8d7da;
            color: #721c24;
        }
    </style>
    ''', unsafe_allow_html=True)